branches:
  - master

tagFormat: "v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: major
        - revert: true
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: patch
        - type: docs
          release: patch
        - type: style
          release: patch
        - type: chore
          release: patch
        - type: refactor
          release: patch
        - type: test
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: revert
            section: Reverts
          - type: docs
            section: Documentation
          - type: style
            section: Styles
          - type: chore
            section: Miscellaneous Chores
          - type: refactor
            section: Code Refactoring
          - type: test
            section: Tests
          - type: build
            section: Build System
          - type: ci
            section: Continuous Integration

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  - - "@semantic-release/exec"
    - verifyConditionsCmd: ./scripts/verify-crates-ready-for-trusted-publishing.sh
      prepareCmd: ./scripts/bump-version.sh ${nextRelease.version}
      publishCmd: ./scripts/publish-crates.sh
      successCmd: |
        echo "new_release_published=true" >> $GITHUB_OUTPUT
        echo "new_release_version=${nextRelease.version}" >> $GITHUB_OUTPUT

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - Cargo.toml
        - crates/uniffi/jvm/build.gradle.kts
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - labels: false
