branches:
  - master

tagFormat: "v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  - - "@semantic-release/exec"
    - verifyConditionsCmd: ./scripts/verify-crates-ready-for-trusted-publishing.sh
      prepareCmd: ./scripts/bump-version.sh ${nextRelease.version}
      publishCmd: ./scripts/publish-crates.sh
      successCmd: |
        echo "new_release_published=true" >> $GITHUB_OUTPUT
        echo "new_release_version=${nextRelease.version}" >> $GITHUB_OUTPUT

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - Cargo.toml
        - crates/uniffi/jvm/build.gradle.kts
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - "@semantic-release/github"
