# bolivar - Fast PDF text extraction
#
# Python bindings for the bolivar Rust library.

from bolivar._bolivar import (
    LAParams,
    PDFDocument,
    PDFPage,
    LTPage,
    LTChar,
    extract_text,
    extract_text_from_path,
    extract_pages,
    extract_pages_with_images,
    extract_pages_from_path,
    extract_pages_with_images_from_path,
    extract_pages_async,
    async_runtime_poc,
    process_page,
    process_pages,
    extract_tables_stream_from_document,
    _extract_tables_core,
    extract_tables_from_document,
    extract_tables_from_document_pages,
    extract_tables_from_ltpage,
    extract_tables_from_page,
    extract_table_from_page,
    extract_tables_from_page_filtered,
    extract_table_from_page_filtered,
    repair_pdf,
    extract_words_from_page,
    extract_text_from_page,
    __version__,
)

__all__ = [
    "LAParams",
    "PDFDocument",
    "PDFPage",
    "LTPage",
    "LTChar",
    "extract_text",
    "extract_text_from_path",
    "extract_pages",
    "extract_pages_with_images",
    "extract_pages_from_path",
    "extract_pages_with_images_from_path",
    "extract_pages_async",
    "async_runtime_poc",
    "process_page",
    "process_pages",
    "extract_tables_stream_from_document",
    "extract_tables_from_document",
    "extract_tables_from_document_pages",
    "extract_tables_from_ltpage",
    "extract_tables_from_page",
    "extract_table_from_page",
    "extract_tables_from_page_filtered",
    "extract_table_from_page_filtered",
    "repair_pdf",
    "extract_words_from_page",
    "extract_text_from_page",
    "__version__",
]
