"""Single source of truth for bolivar Python export surfaces."""

from __future__ import annotations

TOP_LEVEL_EXPORTS = (
    "LAParams",
    "LTChar",
    "LTPage",
    "PDFDocument",
    "PDFPage",
    "__version__",
    "extract_pages",
    "extract_pages_async",
    "extract_pages_from_path",
    "extract_pages_with_images",
    "extract_pages_with_images_from_path",
    "extract_text",
    "extract_text_from_path",
    "process_page",
    "process_pages",
    "repair_pdf",
)

PUBLIC_EXPORTS = (
    "INF",
    "KWD",
    "LIT",
    "MATRIX_IDENTITY",
    "Arcfour",
    "CCITTFaxDecoder",
    "CCITTG4Parser",
    "CMap",
    "CMapDB",
    "EncodingDB",
    "HOCRConverter",
    "HTMLConverter",
    "IdentityCMap",
    "IdentityCMapByte",
    "ImageWriter",
    "LAParams",
    "LTAnno",
    "LTChar",
    "LTCurve",
    "LTFigure",
    "LTImage",
    "LTLine",
    "LTPage",
    "LTRect",
    "LTTextBoxHorizontal",
    "LTTextBoxVertical",
    "LTTextLineHorizontal",
    "LTTextLineVertical",
    "NumberTree",
    "PDFCIDFont",
    "PDFDocEncoding",
    "PDFDocument",
    "PDFFont",
    "PDFPage",
    "PDFParser",
    "PDFResourceManager",
    "PDFStream",
    "PSBaseParser",
    "PSKeyword",
    "PSLiteral",
    "PSStackParser",
    "Plane",
    "TagExtractor",
    "TextConverter",
    "UnicodeMap",
    "XMLConverter",
    "__version__",
    "apply_matrix_pt",
    "apply_matrix_rect",
    "ascii85decode",
    "asciihexdecode",
    "decode_text",
    "extract_pages",
    "extract_pages_async",
    "extract_pages_from_path",
    "extract_pages_with_images",
    "extract_pages_with_images_from_path",
    "extract_text",
    "extract_text_from_path",
    "font_metrics",
    "format_int_alpha",
    "format_int_roman",
    "get_widths",
    "glyphname2unicode",
    "isnumber",
    "latin_encoding",
    "lzwdecode",
    "lzwdecode_with_earlychange",
    "mult_matrix",
    "name2unicode",
    "process_page",
    "process_pages",
    "reorder_text_for_output",
    "repair_pdf",
    "rldecode",
    "safe_cmyk",
    "safe_float",
    "safe_int",
    "safe_matrix",
    "safe_rect",
    "safe_rect_list",
    "safe_rgb",
    "shorten_str",
    "translate_matrix",
    "unpad_aes",
)

BRIDGE_EXPORTS = (
    "_extract_tables_for_page_indexed",
    "_extract_tables_for_compat_page",
    "_extract_words_for_page_indexed",
)

NATIVE_EXTENSION_EXPORTS = (
    "KEYWORD_ARRAY_BEGIN",
    "KEYWORD_ARRAY_END",
    "KEYWORD_DICT_BEGIN",
    "KEYWORD_DICT_END",
    "KEYWORD_PROC_BEGIN",
    "KEYWORD_PROC_END",
)

STUB_SUPPORT_SYMBOLS = (
    "_AsyncPageStream",
    "_Color",
    "_DashingStyle",
    "_Matrix",
    "_PathSegment",
    "_Point",
    "_Rect",
)

STUB_SYMBOLS = (
    PUBLIC_EXPORTS + BRIDGE_EXPORTS + NATIVE_EXTENSION_EXPORTS + STUB_SUPPORT_SYMBOLS
)

STUB_EXPORTS = PUBLIC_EXPORTS + NATIVE_EXTENSION_EXPORTS + BRIDGE_EXPORTS
STUB_SYMBOLS = STUB_EXPORTS + STUB_SUPPORT_SYMBOLS
